[package]
name = "gst_learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
env_logger = "0.9.0"
glib = "0.15.5"
gstreamer = "0.18.3"
log = "0.4.14"
